### ISSUE TITLE
Incorrect URL for AMMessenger API

### ISSUE THREAD

**Issue by mundomatt** [kulbakin/psigate#1]
In Version 1.1.17 of PSiGate's documentation for the Account Manager API you need to send test transactions to `https://accountsstaging.psigate.com/xml`. This cannot be accomplished with the current implementation of `AMMessenger.php` because the constructor modifies the given host URL.

`$this->_url = 'https://'.$host.'/Messenger/AMMessenger';`

**Comment by raoulduke** [comment]
This same change is also needed in the XML Messenger API.

**Comment by kulbakin** [comment]
@mundomatt @raoulduke 

Thank you mates for bringing the issue up. I didn't used your pulls directly since I decided there is no point to leaving `https` part out, if user needs control over entire URL, not just host, than let it be so. But your input was sure helpful.

Also added relevant disclaimer into README file.
